/**
 * ============================================================================
 * SHARED DATA LAYER - All Agents Can Access This
 * ============================================================================
 * 
 * This file defines the data structures that ALL agents can read from.
 * For write access, see each agent's individual README.md
 * 
 * UI Location: N/A (Backend data layer)
 */

// Student data - All agents can READ, Tutor Agent can WRITE (conversation history)
export interface Student {
  id: string;
  name: string;
  email: string;
  grade: string;
  subjects: string[];
  learningStyle: 'visual' | 'auditory' | 'kinesthetic' | 'mixed';
  currentLevel: 'beginner' | 'intermediate' | 'advanced';
  xp: number;
  streak: number;
  achievements: string[];
  lastActive: Date;
}

// Conversation/Memory - Tutor Agent READ/WRITE, Others READ-ONLY
export interface Conversation {
  id: string;
  studentId: string;
  subject: string;
  messages: Message[];
  summary: string; // AI-generated summary for context
  createdAt: Date;
  updatedAt: Date;
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
  metadata?: {
    intent?: string;
    sentiment?: 'positive' | 'neutral' | 'negative';
    topic?: string;
  };
}

// Curriculum data - All agents READ-ONLY
export interface Curriculum {
  id: string;
  subject: string;
  grade: string;
  modules: Module[];
  learningObjectives: string[];
}

export interface Module {
  id: string;
  title: string;
  description: string;
  lessons: Lesson[];
  order: number;
}

export interface Lesson {
  id: string;
  title: string;
  content: string;
  difficulty: 'easy' | 'medium' | 'hard';
  estimatedTime: number; // minutes
  prerequisites: string[];
}

// Quiz/Assessment data - Content Generator WRITE, Grading Agent READ/WRITE (scores)
export interface Quiz {
  id: string;
  lessonId: string;
  title: string;
  questions: Question[];
  timeLimit?: number;
  totalPoints: number;
}

export interface Question {
  id: string;
  type: 'multiple_choice' | 'short_answer' | 'essay' | 'math';
  question: string;
  options?: string[];
  correctAnswer: string;
  explanation: string;
  points: number;
  difficulty: 'easy' | 'medium' | 'hard';
}

// Student progress - Live Monitor WRITE, Others READ-ONLY
export interface ProgressData {
  studentId: string;
  lessonId: string;
  completion: number; // 0-100
  quizScores: QuizScore[];
  timeSpent: number; // minutes
  struggles: string[]; // Topics student struggled with
  strengths: string[]; // Topics student excelled at
  lastUpdated: Date;
}

export interface QuizScore {
  quizId: string;
  score: number;
  maxScore: number;
  answers: StudentAnswer[];
  submittedAt: Date;
}

export interface StudentAnswer {
  questionId: string;
  studentAnswer: string;
  isCorrect: boolean;
  aiFeedback?: string; // Generated by Grading Agent
}

// Live session data - Live Monitor READ/WRITE, Briefing Agent READ-ONLY
export interface LiveSession {
  id: string;
  tutorId: string;
  students: string[];
  subject: string;
  status: 'scheduled' | 'active' | 'ended';
  startTime: Date;
  endTime?: Date;
  
  // Real-time monitoring data
  engagement: Map<string, number>; // studentId -> engagement score 0-100
  confusionAlerts: ConfusionAlert[];
  participation: Map<string, number>; // studentId -> messages count
}

export interface ConfusionAlert {
  studentId: string;
  timestamp: Date;
  topic: string;
  confidence: number; // AI confidence 0-1
  suggestedAction: string;
}

// Tutor profile - Briefing Agent READ-ONLY
export interface Tutor {
  id: string;
  name: string;
  subjects: string[];
  expertise: string[];
  teachingStyle: 'socratic' | 'directive' | 'facilitative';
  ratings: number;
  totalSessions: number;
}

// Data access functions (implementations would connect to DB)
export async function getStudent(studentId: string): Promise<Student | null> {
  // Implementation: Fetch from database
  return null;
}

export async function getConversation(studentId: string, subject: string): Promise<Conversation | null> {
  // Implementation: Fetch from database
  return null;
}

export async function saveMessage(conversationId: string, message: Message): Promise<void> {
  // Implementation: Save to database
}

export async function getCurriculum(subject: string, grade: string): Promise<Curriculum | null> {
  // Implementation: Fetch from database
  return null;
}

export async function getProgress(studentId: string, lessonId: string): Promise<ProgressData | null> {
  // Implementation: Fetch from database
  return null;
}

export async function getLiveSession(sessionId: string): Promise<LiveSession | null> {
  // Implementation: Fetch from database
  return null;
}
