/**
 * Built-in virtual-background wallpapers offered to tutors. The PNGs are
 * generated by scripts/gen-video-backgrounds.js into public/video-backgrounds/
 * and served same-origin so Daily's background-image processor can load them.
 */
export interface VideoBackground {
  id: string
  label: string
  url: string
}

export const VIDEO_BACKGROUNDS: VideoBackground[] = [
  { id: 'slate', label: 'Slate', url: '/video-backgrounds/slate.png' },
  { id: 'ocean', label: 'Ocean', url: '/video-backgrounds/ocean.png' },
  { id: 'sunset', label: 'Sunset', url: '/video-backgrounds/sunset.png' },
  { id: 'forest', label: 'Forest', url: '/video-backgrounds/forest.png' },
  { id: 'aurora', label: 'Aurora', url: '/video-backgrounds/aurora.png' },
  { id: 'rose', label: 'Rose', url: '/video-backgrounds/rose.png' },
]
