/**
 * Built-in virtual-background options offered to tutors, served same-origin from
 * public/video-backgrounds/ so Daily's background-image processor can load them:
 *  - Colors: gradient PNGs generated by scripts/gen-video-backgrounds.js
 *  - Photos: royalty-free images (Unsplash license) in ./photos/
 */
export interface VideoBackground {
  id: string
  label: string
  url: string
  kind: 'color' | 'photo'
}

export const VIDEO_BACKGROUNDS: VideoBackground[] = [
  // Gradient colors
  { id: 'slate', label: 'Slate', url: '/video-backgrounds/slate.png', kind: 'color' },
  { id: 'ocean', label: 'Ocean', url: '/video-backgrounds/ocean.png', kind: 'color' },
  { id: 'sunset', label: 'Sunset', url: '/video-backgrounds/sunset.png', kind: 'color' },
  { id: 'forest', label: 'Forest', url: '/video-backgrounds/forest.png', kind: 'color' },
  { id: 'aurora', label: 'Aurora', url: '/video-backgrounds/aurora.png', kind: 'color' },
  { id: 'rose', label: 'Rose', url: '/video-backgrounds/rose.png', kind: 'color' },
  // Photo backgrounds
  { id: 'office', label: 'Office', url: '/video-backgrounds/photos/office.jpg', kind: 'photo' },
  { id: 'library', label: 'Library', url: '/video-backgrounds/photos/library.jpg', kind: 'photo' },
  {
    id: 'living-room',
    label: 'Living room',
    url: '/video-backgrounds/photos/living-room.jpg',
    kind: 'photo',
  },
  { id: 'lounge', label: 'Lounge', url: '/video-backgrounds/photos/lounge.jpg', kind: 'photo' },
  {
    id: 'apartment',
    label: 'Apartment',
    url: '/video-backgrounds/photos/apartment.jpg',
    kind: 'photo',
  },
]
