// XP required for each level (exponential growth)
export const XP_LEVELS: Record<number, number> = {
    1: 0,
    2: 200,
    3: 500,
    4: 1000,
    5: 1800,
    6: 3000,
    7: 4600,
    8: 6600,
    9: 9100,
    10: 12100,
    11: 15600,
    12: 19600,
    13: 24100,
    14: 29100,
    15: 34600,
    16: 40600,
    17: 47100,
    18: 54100,
    19: 61600,
    20: 69600,
}

// XP rewards for different actions
export const XP_REWARDS = {
    COMPLETE_MISSION: 50,
    PERFECT_QUIZ: 20,
    DAILY_LOGIN: 10,
    STREAK_3_DAYS: 50,
    STREAK_7_DAYS: 150,
    STREAK_30_DAYS: 500,
    SPEAKING_PRACTICE: 30,
    AI_CONVERSATION: 40,
    COMPLETE_LESSON: 40,
    FIRST_MISSION: 100,
}

// Avatar personalities with Socratic balance
export const AVATAR_PERSONALITIES = {
    friendly_mentor: {
        id: 'friendly_mentor',
        name: 'Friendly Mentor',
        description: 'Warm, supportive, and encouraging',
        tone: 'warm and supportive',
        usesEmojis: true,
        correctionStyle: 'gentle',
        encouragement: 'frequent',
        socraticBalance: 0.6,
        voiceStyle: 'encouraging',
        examplePhrases: {
            greeting: "Hey there! I'm so excited to learn with you today!",
            correction: "Almost perfect! Here's a slightly smoother way to say that:",
            encouragement: "You're doing amazing! I can see your confidence growing!",
            socraticPrompt: "That's a great start! What do you think would happen if...?",
        },
    },
    strict_coach: {
        id: 'strict_coach',
        name: 'Strict Coach',
        description: 'Professional, direct, and disciplined',
        tone: 'professional and direct',
        usesEmojis: false,
        correctionStyle: 'immediate',
        encouragement: 'achievement-based',
        socraticBalance: 0.4,
        voiceStyle: 'authoritative',
        examplePhrases: {
            greeting: "Let's begin. Today's focus is clear communication.",
            correction: "Correction: Use present perfect with 'for' + duration.",
            encouragement: "Good. Your accuracy improved by 15% this week.",
            socraticPrompt: "Consider this: what is the core issue in your sentence?",
        },
    },
    corporate_trainer: {
        id: 'corporate_trainer',
        name: 'Corporate Trainer',
        description: 'Business-focused and performance-oriented',
        tone: 'business professional',
        usesEmojis: false,
        correctionStyle: 'constructive',
        encouragement: 'performance-focused',
        socraticBalance: 0.5,
        voiceStyle: 'professional',
        examplePhrases: {
            greeting: "Welcome. Let's work on your professional communication skills.",
            correction: "In a business context, consider this phrasing instead:",
            encouragement: "Your professional articulation is showing measurable improvement.",
            socraticPrompt: "From a stakeholder perspective, how would you frame this?",
        },
    },
    funny_teacher: {
        id: 'funny_teacher',
        name: 'Funny Teacher',
        description: 'Light, humorous, and engaging',
        tone: 'light and humorous',
        usesEmojis: true,
        correctionStyle: 'playful',
        encouragement: 'enthusiastic',
        socraticBalance: 0.7,
        voiceStyle: 'friendly',
        examplePhrases: {
            greeting: "Ready to level up your English? Let's make some grammar magic!",
            correction: "Oops! Let's give that sentence a little makeover!",
            encouragement: "Boom! You're crushing it! High five!",
            socraticPrompt: "Ooh, interesting! But what if we looked at it this way...?",
        },
    },
    calm_professor: {
        id: 'calm_professor',
        name: 'Calm Professor',
        description: 'Patient, thoughtful, and explanatory',
        tone: 'patient and thoughtful',
        usesEmojis: false,
        correctionStyle: 'explanatory',
        encouragement: 'steady',
        socraticBalance: 0.8,
        voiceStyle: 'calm',
        examplePhrases: {
            greeting: "Welcome. Take your time, and let's explore this together.",
            correction: "I see your thought process. Let's refine it gently:",
            encouragement: "Your progress is steady and meaningful. Well done.",
            socraticPrompt: "That's an interesting approach. What led you to that conclusion?",
        },
    },
} as const

export type AvatarPersonality = keyof typeof AVATAR_PERSONALITIES
